name = "firehose-space"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Main D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "firehose-db"
database_id = "24fc6bed-8bc6-4b72-be83-0f7d246a6174"

# Main KV namespace binding
[[kv_namespaces]]
binding = "CACHE"
id = "112f09795aa74b2081f17a65346cc0d1"

[env.production]
name = "firehose-space"
route = { pattern = "firehose.space/api/*", zone_name = "firehose.space" }

[env.production.vars]
ENVIRONMENT = "production"
SITE_URL = "https://firehose.space"

[[env.production.d1_databases]]
binding = "DB"
database_name = "firehose-db"
database_id = "24fc6bed-8bc6-4b72-be83-0f7d246a6174"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "112f09795aa74b2081f17a65346cc0d1"

[env.development]
name = "firehose-space-dev"

[env.development.vars]
ENVIRONMENT = "development"
SITE_URL = "http://localhost:3000"

[[env.development.d1_databases]]
binding = "DB"
database_name = "firehose-db"
database_id = "24fc6bed-8bc6-4b72-be83-0f7d246a6174"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "112f09795aa74b2081f17a65346cc0d1"

# Cron triggers disabled temporarily for initial deployment
# [[triggers.crons]]
# crons = ["0 */1 * * *"]  # Every hour
